### ISSUE TITLE
need new version in Metadata.jl

### ISSUE THREAD

**Issue by catawbasam** [JuliaAstro/AstroLib.jl#14]
I'm seeing multiple stack traces related to `@vectorize_1arg` and `@vectorize_2arg`  upon running `using AstroLib` from Julia 0.6.  

Looks like you've updated master, so maybe just need to tag a version in Metadata.jl?

**Comment by giordano** [comment]
Yes, that's fixed in `master`, but this version only supports Julia 0.6 (there were a couple of small incompatibilities between Julia 0.5 and 0.6, not fixable with `Compat`), which isn't released yet, it took way more than expected to be finished.  However, Julia 0.6 should be released very soon now, I plan to roll a new version of AstroLib.jl within next few days (maybe today or tomorrow).  Thanks!

**Comment by giordano** [comment]
Version 0.1.0 released (only for Julia 0.6, sorry)!
