### ISSUE TITLE
Consider MJD functions

### ISSUE THREAD

**Issue by pasha2718** [JuliaAstro/AstroLib.jl#49]
I'm happy to keep adding and subtracting 2400000.5, but I'll suggest making some functions complimentary to daycnv() that use MJD.  In the telescope data I'm using, MJD is dominant, and it's easy to miss a zero or forget that historically buggy 0.5. Thanks.

**Comment by giordano** [comment]
Thanks for the suggestion, I'm happy to see that this is being used! :-)

I'm not sure I'll fix this issue because, once released, [`AstronomicalTime.jl`](https://github.com/JuliaAstro/AstronomicalTime.jl) should be a better solution for time-related astrostuff.

For the time being, please note that you can use [`juldate`](https://juliaastro.github.io/AstroLib.jl/stable/ref.html#AstroLib.juldate-Tuple{DateTime}) to covert a `DateTime` to *Reduced* Julian Day, which is half day off what you would like.  This is more accurate than manually subtracting 2.4e6 days.

**Comment by pasha2718** [comment]
Sounds good.  I'll keep using AstroLib because I need the LST conversions too, but will go over to `juldate` for other operations.  I'll close this issue then.
